# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('gabinete', models.CharField(max_length=200)),
                ('anexo', models.CharField(max_length=200)),
                ('aniversario', models.DateTimeField(verbose_name=b'date published')),
                ('profissoes', models.CharField(max_length=200)),
                ('nome_civil', models.CharField(max_length=200)),
                ('tratamento', models.CharField(max_length=200)),
            ],
        ),
    ]
