# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('indicado', models.CharField(max_length=200)),
                ('condicao', models.CharField(max_length=200)),
            ],
        ),
    ]
