# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0003_parlamentar_comissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('ano', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.AddField(
            model_name='parlamentar',
            name='frentes',
            field=models.ManyToManyField(to='acao.Frentes'),
        ),
    ]
