# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acao', '0004_auto_20160131_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('ano', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='FrenteParlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('invite_reason', models.CharField(max_length=64)),
                ('frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acao.Frente')),
            ],
        ),
        migrations.RemoveField(
            model_name='parlamentar',
            name='comissoes',
        ),
        migrations.RemoveField(
            model_name='parlamentar',
            name='frentes',
        ),
        migrations.DeleteModel(
            name='Frentes',
        ),
        migrations.AddField(
            model_name='frenteparlamentar',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acao.Parlamentar'),
        ),
        migrations.AddField(
            model_name='frente',
            name='parlamentar',
            field=models.ManyToManyField(through='acao.FrenteParlamentar', to='acao.Parlamentar'),
        ),
    ]
